### PR TITLE
Use direct function calls if the driver used is hyperv

### PR DESCRIPTION
**Pull request by guillaumerose**
Use direct function calls if the driver used is hyperv

This prevents machine to exec an other program and connect to 127.0.0.1.
It will solve some Windows VM creation issues with VPN enabled like
Cisco AnyConnect (dial-http tcp 127.0.0.1:54615: unexpected EOF error).

Related to https://github.com/code-ready/crc/issues/1600 - will go to the next error
Related to https://github.com/code-ready/crc/issues/1087

Tested with crc with this patch: https://github.com/guillaumerose/crc/commit/49fd705ddb49b60c8983c3d52f085c070f5ae92f

### CODE REVIEW

**Comment by cfergeau** [comment]
I'd expect some details on "It will solve some Windows VM creation issues with VPN enabled". Iirc, it was very much on purpose that hyperv lived in a separate process, has this change been discussed outside of this PR?

**Comment by guillaumerose** [comment]
I don't see a need for running hyperv package in an other process. It only runs un-elevated powershell commands. 
Yes it breaks the symmetry with others drivers but at least it will help some users.

I added more details in the commit log.

**Comment by gbraad** [comment]
Hyper-V never posed an issue... it was Hyperkit that had issues to live in a different process so it could remain long-running, as when the mainn program would terminate, the VM would disappear. This is not the case on Windows/Hyper-V

**Comment by gbraad** [comment]
Hyper-V never posed an issue... it was Hyperkit that had issues to live in a different process so it could remain long-running, as when the mainn program would terminate, the VM would disappear. This is not the case on Windows/Hyper-V

**Review by gbraad — APPROVED** [review]

**Comment by gbraad** [comment]
this solves oft seen issues with application firewalls or other network inspection tools

**Pull request merged**
